/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary":                    "#00466f",
        "primary-container":          "#1f5e8c",
        "on-primary":                 "#ffffff",
        "on-primary-fixed":           "#001d32",
        "primary-fixed":              "#cee5ff",
        "primary-fixed-dim":          "#96ccff",
        "on-primary-fixed-variant":   "#004a76",
        "on-primary-container":       "#add6ff",
        "inverse-primary":            "#96ccff",
        "surface-tint":               "#256291",
        "secondary":                  "#226a4b",
        "secondary-container":        "#a9f2ca",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#297151",
        "on-secondary-fixed":         "#002113",
        "on-secondary-fixed-variant": "#005235",
        "secondary-fixed":            "#a9f2ca",
        "secondary-fixed-dim":        "#8ed5af",
        "tertiary":                   "#5e3c00",
        "tertiary-container":         "#7d5100",
        "on-tertiary":                "#ffffff",
        "on-tertiary-fixed":          "#291800",
        "on-tertiary-fixed-variant":  "#633f00",
        "tertiary-fixed":             "#ffddb4",
        "tertiary-fixed-dim":         "#ffb955",
        "on-tertiary-container":      "#ffc980",
        "surface":                    "#f7f9fc",
        "surface-dim":                "#d8dadd",
        "surface-bright":             "#f7f9fc",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f2f4f7",
        "surface-container":          "#eceef1",
        "surface-container-high":     "#e6e8eb",
        "surface-container-highest":  "#e0e3e6",
        "surface-variant":            "#e0e3e6",
        "on-surface":                 "#191c1e",
        "on-surface-variant":         "#41474f",
        "inverse-surface":            "#2d3133",
        "inverse-on-surface":         "#eff1f4",
        "outline":                    "#717880",
        "outline-variant":            "#c1c7d0",
        "background":                 "#f7f9fc",
        "on-background":              "#191c1e",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "on-error-container":         "#93000a",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "1.5rem",
        "2xl":   "2rem",
        "3xl":   "3rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
}
